language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install numpy numba batman-package scipy tqdm argparse astroquery
script:
  - cd transitleastsquares
  - ls
  - python tests.py
  - ls
